-- public.restaurante definition

-- Drop table

-- DROP TABLE public.restaurante;

CREATE TABLE public.restaurante (
	idrestaurante int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cnpj varchar(255) NULL,
	dataatualizacao timestamp NULL,
	datacriacao timestamp NULL,
	nome varchar(255) NULL,
	proprietario varchar(255) NULL,
	idlocalizacao int8 NULL,
	CONSTRAINT restaurante_pkey PRIMARY KEY (idrestaurante)
);


-- public.restaurante foreign keys

ALTER TABLE public.restaurante ADD CONSTRAINT fkbyl0klnghs0p8m9rfw46lud46 FOREIGN KEY (idlocalizacao) REFERENCES public.localizacao(idlocalizacao);



-- public.prato definition

-- Drop table

-- DROP TABLE public.prato;

CREATE TABLE public.prato (
	idprato int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	descricao varchar(255) NULL,
	nome varchar(255) NULL,
	preco numeric(19, 2) NULL,
	idrestaurante int8 NULL,
	CONSTRAINT prato_pkey PRIMARY KEY (idprato)
);


-- public.prato foreign keys

ALTER TABLE public.prato ADD CONSTRAINT fkl7qikbp63ydge7166uf7fp1e6 FOREIGN KEY (idrestaurante) REFERENCES public.restaurante(idrestaurante);

